data:
  # train_files: hiyouga/math12k@train
  # val_files: hiyouga/math12k@test
  prompt_key: prompt
  answer_key: answer
  image_key: image
  video_key: video
  image_dir: "../../data/Train"
  video_fps: 2.0
  max_prompt_length: 15000
  max_response_length: 1536
  rollout_batch_size: 512  # equivalent to verl's data.train_batch_size
  mini_rollout_batch_size: null  # equivalent to verl's data.gen_batch_size
  val_batch_size: 1024
  # format_prompt: ./examples/format_prompt/math.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 262144
  max_pixels: 1568000
  filter_overlong_prompts: false

algorithm:
  adv_estimator: router # grpo
  disable_kl: true
  use_kl_loss: false
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: true  # dapo filter groups
  filter_key: overall
  filter_low: 0.01
  filter_high: 6.9

worker:
  actor:
    global_batch_size: 32  # equivalent to verl's actor.ppo_mini_batch_size
    micro_batch_size_per_device_for_update: 1  # equivalent to verl's actor.]
    micro_batch_size_per_device_for_experience: 2  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    clip_ratio_low: 0.2
    clip_ratio_high: 0.28
    model:
      # model_path: ../models/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: true
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 8
    temperature: 1.0
    top_p: 1.0
    limit_images: 5
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    disable_tqdm: false
    val_override_config:
      temperature: 0.1
      top_p: 0.95
      n: 1
    max_num_batched_tokens: 20000

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/evidencecot.py:sum_all

trainer:
  total_epochs: 16
  max_steps: null
  project_name: easy_r1
  experiment_name: qwen2_5_7b_evidence_grpo
  logger: ["console", "tensorboard"]
  nnodes: 1
  n_gpus_per_node: 8
  max_try_make_batch: 20  # -1 means no limit
  val_freq: 10  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 5
  save_freq: 10  # -1 to disable
  save_limit: 8  # -1 to disable
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true
